INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Valencia', 'Valencia', '16', '21', '7', '0', '1');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Atletico de Madrid', 'Madrid', '19', '20', '6', '2', '0');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Madrid', 'Madrid', '18', '19', '6', '1', '1');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Barcelona', 'Barcelona', '18', '16', '5', '1', '1');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Athletic Club', 'Bilbao', '16', '15', '4', '3', '1');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Osasuna', 'Pamplona', '13', '14', '4', '2', '2');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Mallorca', 'Mallorca', '10', '12', '3', '3', '2');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Las Palmas', 'Gran Canaria', '9', '12', '3', '3', '2');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Cadiz', 'Cadiz', '9', '10', '3', '1', '4');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Sevilla', 'Sevilla', '9', '10', '3', '1', '4');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Betis', 'Sevilla', '10', '9', '2', '3', '3');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Almeria', 'Almeria', '8', '9', '2', '3', '3');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Granada', 'Granada', '10', '8', '2', '2', '4');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Villarreal', 'Castellon', '4', '8', '2', '2', '4');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Getafe', 'Madrid', '11', '7', '2', '1', '4');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Rayo Vallecano', 'Madrid', '11', '7', '1', '4', '3');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Celta de Vigo', 'Vigo', '6', '7', '2', '1', '5');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Real Sociedad', 'San Sebastian', '8', '5', '1', '2', '5');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Alaves', 'Avila', '13', '5', '1', '2', '5');
INSERT INTO `laliga`.`equipos` (`nombre`, `ciudad`, `goles`, `puntos`, `victorias`, `empates`, `derrotas`) VALUES ('Girona', 'Gerona', '11', '3', '0', '3', '5');
